stages:
  - build
  - archive
  - trace
  - pre_fuzz
  - fuzz

variables:
  LC_ALL: "en_US.UTF-8"
  LANG: "en_US.UTF-8"
  DOCKER_DRIVER: overlay2
  DOCKER_TLS_CERTDIR: ""

build:
  stage: build
  script:
    - make
  retry: 2
  artifacts:
    paths:
      - target/bin
      - target/include
      - target/frameworks
  tags:
    - macos

archive:
  stage: archive
  script:
    - make framework
  retry: 2
  artifacts:
    paths:
      - nGit.xcframework
  tags:
    - macos

fuzz_build:
  stage: pre_fuzz
  image: docker:19.03.0
  script:
    - docker build -f fuzz/Dockerfile . -t registry.nocsi.org/ngit:fuzz
    - docker push registry.nocsi.org/ngit-lib:fuzz
  tags:
    - docker
